/* ==========================================================================
   DeckWidgets — the five interactive panels.

   Each widget registers { init, run, reset }. The deck chrome maps B -> run and
   R -> reset for whichever interactive slide is on screen, so every demo is
   driveable from the clicker without touching the mouse.
   ========================================================================== */
window.DeckWidgets = (function () {
  'use strict';

  const registry = new Map();   // element -> { run, reset }
  const nf = (n) => Math.round(n).toLocaleString('en-US');
  const $ = (root, role) => root.querySelector(`[data-role="${role}"]`);
  const $$ = (root, role) => Array.from(root.querySelectorAll(`[data-role="${role}"]`));

  /* ======================================================================
     1. Generator pipeline — one attribute in, a whole file out
     ====================================================================== */
  const KINDS = {
    Int: {
      clr: 'int', base: 'IntEnum', low: '1', high: '2',
      read: 'r.GetInt32()', write: 'w.WriteNumberValue(v.Value)'
    },
    String: {
      clr: 'string', base: 'StringEnum', low: '"low"', high: '"high"',
      read: 'r.GetString()!', write: 'w.WriteStringValue(v.Value)'
    },
    Guid: {
      clr: 'Guid', base: 'GuidEnum', low: 'Guid.Parse("a1b2...")', high: 'Guid.Parse("c3d4...")',
      read: 'r.GetGuid()', write: 'w.WriteStringValue(v.Value)'
    }
  };

  const inputSrc = (kind) => {
    const k = KINDS[kind];
    return `[GeneratedEnum(EnumType.${kind})]
public sealed partial class Priority
{
    public required string Name { get; init; }

    public static Priority Low  { get; }
        = new() { Value = ${k.low}, Name = "Low" };

    public static Priority High { get; }
        = new() { Value = ${k.high}, Name = "High" };
}

// 'Value' is never declared here.
// The generated base list brings it in.`;
  };

  const outputSrc = (kind) => {
    const k = KINDS[kind];
    return `// <auto-generated/>  Priority.g.cs  — never touched by hand
[JsonConverter(typeof(PriorityJsonConverter))]
public sealed partial class Priority : ${k.base}<Priority>;
// Value and All come from the hand-written ${k.base}<T> base.

public sealed class PriorityJsonConverter : JsonConverter<Priority>
{
    public override Priority Read(
        ref Utf8JsonReader r, Type t, JsonSerializerOptions o)
    {
        var v = ${k.read};                  // a ref param can't be captured
        return Priority.All.Single(x => x.Value == v);
    }

    public override void Write(
        Utf8JsonWriter w, Priority v, JsonSerializerOptions o)
        => ${k.write};
}

public sealed class PrioritySqlConverter()
    : ValueConverter<Priority, ${k.clr}>(
        convertToProviderExpression:   x => x.Value,
        convertFromProviderExpression: x =>
            Priority.All.Single(a => a.Value == x));`;
  };

  function initPipeline(el) {
    const section = el.closest('section');
    const bar = section.querySelector('[data-widget="pipeline-toolbar"]');
    const inCode = $(el, 'input-code');
    const outCode = $(el, 'output-code');
    const out = $(el, 'output');
    const stats = $(section, 'stats');
    let kind = 'Int';
    let busy = false;

    function paintInput() {
      DeckCode.paint(inCode, inputSrc(kind), 'csharp');
    }

    function reset() {
      busy = false;
      el.classList.remove('running');
      out.classList.remove('done');
      outCode.innerHTML = '';
      stats.classList.remove('in');
      $(stats, 'stat-lines').textContent = '0';
      paintInput();
    }

    function run() {
      if (busy) return;
      busy = true;
      el.classList.add('running');
      out.classList.remove('done');
      outCode.innerHTML = '';
      stats.classList.remove('in');
      // a beat of "compiling", then the file streams in line by line
      setTimeout(() => {
        el.classList.remove('running');
        out.classList.add('done');
        DeckCode.paint(outCode, outputSrc(kind), 'csharp', { stagger: 24 }).then((n) => {
          $(stats, 'stat-lines').textContent = nf(n);
          stats.classList.add('in');
          busy = false;
        });
      }, 780);
    }

    bar.querySelectorAll('[data-kind]').forEach((btn) => {
      btn.addEventListener('click', () => {
        bar.querySelectorAll('[data-kind]').forEach((b) => b.setAttribute('aria-selected', 'false'));
        btn.setAttribute('aria-selected', 'true');
        kind = btn.dataset.kind;
        reset();
      });
    });
    $(bar, 'build').addEventListener('click', run);
    $(bar, 'reset').addEventListener('click', reset);

    paintInput();
    registry.set(section, { run, reset });
  }

  /* ======================================================================
     2. Cost calculator — the shape of the two cost curves
     ====================================================================== */
  const LINES_PER_ENUM = 46;   // measured: Priority.g.cs in the demo solution
  const GENERATOR_LINES = 103; // measured: EnumGenerator.cs + EnumBuilder.cs, written once

  function initCalc(el) {
    const section = el.closest('section');
    const slider = $(el, 'slider');

    function update() {
      const n = Number(slider.value);
      const dup = n * LINES_PER_ENUM;
      const gen = GENERATOR_LINES + n;
      const max = Math.max(dup, gen, 1);

      slider.style.setProperty('--pct', ((n - 1) / (slider.max - 1) * 100) + '%');
      $(el, 'n').textContent = n;
      $(el, 'dup-lines').textContent = nf(dup);
      $(el, 'gen-lines').textContent = nf(gen);
      $(el, 'bar-dup').style.width = (dup / max * 100) + '%';
      $(el, 'bar-gen').style.width = (gen / max * 100) + '%';
      $(el, 'places').textContent = n;
      $(el, 'review').textContent = nf(dup);
      $(el, 'drift').textContent = Math.round((1 - Math.pow(0.97, n)) * 100) + '%';
    }

    slider.addEventListener('input', update);
    update();

    // B / R nudge the slider so the story works from a clicker too
    registry.set(section, {
      run: () => { slider.value = Math.min(Number(slider.max), Number(slider.value) + 8); update(); },
      reset: () => { slider.value = 6; update(); }
    });
  }

  /* ======================================================================
     3. IDE simulator — squiggle, light bulb, code fix, green build
     ====================================================================== */
  const CUSTOMER_LINES = [
    [6,  'using MyApp.Demo.Abstractions;'],
    [7,  ''],
    [8,  'namespace MyApp.Demo;'],
    [9,  ''],
    [10, 'public sealed class Customer : EntityBase'],
    [11, '{'],
    [12, '    public required string Name { get; init; }'],
    [13, ''],
    [14, '    public string Adress { get; init; } = "";'],
    [15, '}']
  ];
  const TYPO_LINE = 14;

  function initIde(el) {
    const section = el.closest('section');
    const editor = $(el, 'editor');
    const errors = $(el, 'errors');
    const build = $(el, 'build');
    let fixedAlready = false;

    function paint(word) {
      editor.innerHTML = CUSTOMER_LINES.map(([no, text]) => {
        let src = DeckCode.tokenize(text.replace('Adress', word), 'csharp');
        if (no === TYPO_LINE && !fixedAlready) {
          src = src.replace(word, `<span class="squig" data-role="ident">${word}</span>`);
        }
        return `<div class="row" data-line="${no}">` +
               `<span class="gut">${no}</span>` +
               `<span class="src">${src || ' '}</span></div>`;
      }).join('');

      if (!fixedAlready) {
        const row = editor.querySelector(`.row[data-line="${TYPO_LINE}"]`);
        const bulb = document.createElement('span');
        bulb.className = 'bulb';
        bulb.title = "Show potential fixes";
        bulb.textContent = '\u{1F4A1}';
        row.appendChild(bulb);
        bulb.addEventListener('click', openMenu);
        const squig = row.querySelector('.squig');
        if (squig) squig.addEventListener('click', openMenu);
      }
    }

    function closeMenu() {
      const m = editor.querySelector('.fixmenu');
      if (m) m.remove();
    }

    function openMenu(ev) {
      ev.stopPropagation();
      closeMenu();
      const row = editor.querySelector(`.row[data-line="${TYPO_LINE}"]`);
      const menu = document.createElement('div');
      menu.className = 'fixmenu';
      menu.innerHTML =
        '<div class="hdr">APP1001 &nbsp;&middot;&nbsp; MyApp.CodeFixes</div>' +
        '<button data-role="apply">\u{1F4A1} Rename to \'Address\'</button>' +
        '<button data-role="apply-all">\u{1F4A1} Fix all in solution</button>';
      menu.style.left = '52px';
      menu.style.top = (row.offsetTop + row.offsetHeight + 4) + 'px';
      editor.appendChild(menu);
      menu.querySelectorAll('button').forEach((b) => b.addEventListener('click', applyFix));
    }

    function applyFix(ev) {
      if (ev) ev.stopPropagation();
      closeMenu();
      fixedAlready = true;
      paint('Address');
      // the renamed row gets a brief accent flash
      const row = editor.querySelector(`.row[data-line="${TYPO_LINE}"] .src`);
      if (row) {
        row.style.transition = 'background .6s ease';
        row.style.background = 'color-mix(in oklab, var(--ok) 22%, transparent)';
        setTimeout(() => { row.style.background = 'transparent'; }, 700);
      }
      errors.classList.add('clean');
      errors.innerHTML =
        '<span class="sev">✓ 0 errors</span>' +
        '<span>APP1001 fixed by <b>TypoCodeFixProvider</b> — declaration <em>and</em> every reference renamed</span>' +
        '<span style="margin-left:auto;color:var(--fg-faint)">Customer.cs&nbsp;14</span>';
      build.classList.add('green');
      $(build, 'build-icon').innerHTML = '✓';
      $(build, 'build-text').textContent = 'Build succeeded';
    }

    function reset() {
      fixedAlready = false;
      closeMenu();
      paint('Adress');
      errors.classList.remove('clean');
      errors.innerHTML =
        '<span class="sev">✗ error</span>' +
        "<span><b>APP1001</b>&nbsp; Identifier 'Adress' contains 'Adress' — did you mean 'Address'?</span>" +
        '<span style="margin-left:auto;color:var(--fg-faint)">Customer.cs&nbsp;14</span>';
      build.classList.remove('green');
      $(build, 'build-icon').innerHTML = '✗';
      $(build, 'build-text').textContent = 'Build failed';
    }

    editor.addEventListener('click', closeMenu);
    $(section, 'reset').addEventListener('click', reset);
    reset();
    registry.set(section, { run: () => (fixedAlready ? reset() : applyFix()), reset });
  }

  /* ======================================================================
     4. Layered defence — walk an agent down the funnel
     ====================================================================== */
  function initLayers(el) {
    const section = el.closest('section');
    const layers = Array.from(el.querySelectorAll('.layer'));
    const token = document.createElement('div');
    token.className = 'agent-token';
    token.textContent = '\u{1F916}';
    token.style.top = '0px';
    token.style.opacity = '0';
    el.appendChild(token);
    let timers = [];

    function clearTimers() { timers.forEach(clearTimeout); timers = []; }

    function reset() {
      clearTimers();
      layers.forEach((l) => l.classList.remove('tested', 'pass', 'warn', 'block', 'active'));
      token.classList.remove('stuck');
      token.style.opacity = '0';
      token.style.top = (layers[0].offsetTop - 44) + 'px';
    }

    function run() {
      reset();
      token.style.opacity = '1';
      layers.forEach((layer, i) => {
        timers.push(setTimeout(() => {
          layers.forEach((l) => l.classList.remove('active'));
          layer.classList.add('active');
          token.style.top = (layer.offsetTop + layer.offsetHeight / 2 - 17) + 'px';
          timers.push(setTimeout(() => {
            layer.classList.add('tested', layer.dataset.outcome);
            if (layer.dataset.outcome === 'block') {
              layer.classList.remove('active');
              token.classList.add('stuck');
            }
          }, 420));
        }, 120 + i * 1000));
      });
    }

    $(section, 'run').addEventListener('click', run);
    $(section, 'reset').addEventListener('click', reset);
    // offsetTop needs layout; reveal scales the slide, so defer one frame
    requestAnimationFrame(reset);
    registry.set(section, { run, reset });
  }

  /* ======================================================================
     5. Perf race — the cost of one keystroke, solution-wide
     ====================================================================== */
  const RACE = {
    slow: { nodes: 12000, allocs: 12000, ms: 1840, dur: 3000 },
    fast: { nodes: 900,   allocs: 0,     ms: 62,   dur: 620 }
  };

  function initRace(el) {
    const section = el.closest('section');
    const lanes = {};
    ['slow', 'fast'].forEach((k) => { lanes[k] = el.querySelector(`.lane[data-lane="${k}"]`); });
    let raf = null;

    function paintLane(k, p) {
      const lane = lanes[k];
      const spec = RACE[k];
      $(lane, 'fill').style.width = (p * 100) + '%';
      $(lane, 'nodes').textContent = nf(spec.nodes * p);
      $(lane, 'allocs').textContent = nf(spec.allocs * p);
      $(lane, 'ms').textContent = nf(spec.ms * p) + ' ms';
    }

    function reset() {
      if (raf) cancelAnimationFrame(raf);
      raf = null;
      ['slow', 'fast'].forEach((k) => {
        lanes[k].classList.remove('running', 'finished');
        $(lanes[k], 'done').textContent = '';
        paintLane(k, 0);
      });
    }

    function run() {
      reset();
      ['slow', 'fast'].forEach((k) => lanes[k].classList.add('running'));
      const t0 = performance.now();
      (function tick(now) {
        const t = now - t0;
        let allDone = true;
        ['slow', 'fast'].forEach((k) => {
          const spec = RACE[k];
          const p = Math.min(1, t / spec.dur);
          paintLane(k, p);
          if (p >= 1) {
            if (!lanes[k].classList.contains('finished')) {
              lanes[k].classList.add('finished');
              lanes[k].classList.remove('running');
              $(lanes[k], 'done').textContent =
                `${nf(spec.ms)} ms · ${nf(spec.allocs)} allocations`;
            }
          } else {
            allDone = false;
          }
        });
        raf = allDone ? null : requestAnimationFrame(tick);
      })(t0);
    }

    $(section, 'run').addEventListener('click', run);
    $(section, 'reset').addEventListener('click', reset);
    reset();
    registry.set(section, { run, reset });
  }

  /* ====================================================================== */
  const BUILDERS = {
    pipeline: initPipeline,
    calc: initCalc,
    ide: initIde,
    layers: initLayers,
    race: initRace
  };

  function init() {
    document.querySelectorAll('[data-widget]').forEach((el) => {
      const b = BUILDERS[el.dataset.widget];
      if (b) b(el);
    });
  }

  const forSection = (section) => registry.get(section) || null;

  return { init, forSection };
})();
