using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MyApp.CodeGen;

/// <summary>
/// Incremental source generator. One attribute on a partial class becomes the
/// single source of truth; the compiler emits the repetitive companion member.
///
/// Realistic touch: the generated <c>Value</c> property is <b>typed by the
/// EnumType</b> passed to the attribute (int / string / Guid / byte). The demo's
/// <c>Priority</c> class does not compile without it — generation is load-bearing,
/// not cosmetic.
///
/// Why this is fast:
///  - IIncrementalGenerator (not the legacy ISourceGenerator).
///  - ForAttributeWithMetadataName -> only annotated nodes enter the pipeline.
///  - The model is an equatable readonly record struct, so the pipeline caches
///    and re-generates only when the model actually changes.
///  - The transform step is pure and small; text building happens in the output step.
/// </summary>
[Generator]
public sealed class EnumGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "MyApp.CodeGen.GeneratedEnumAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the marker attribute + EnumType into the consuming compilation.
        // No shared runtime assembly needed — the attribute lives where it's used.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GeneratedEnumAttribute.g.cs", MarkerSource));

        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => ToModel(ctx));

        context.RegisterSourceOutput(models,
            static (spc, model) => spc.AddSource($"{model.ClassName}.g.cs", Build(model)));
    }

    // Pure: extract just the data we need. Returns an equatable value type.
    private static EnumToGenerate ToModel(GeneratorAttributeSyntaxContext ctx)
    {
        var declaration = (ClassDeclarationSyntax)ctx.TargetNode;

        var ns = declaration.FirstAncestorOrSelf<BaseNamespaceDeclarationSyntax>()?.Name.ToString()
                 ?? "GeneratedNamespace";

        // TypedConstant.Value for an enum is the boxed underlying int; the CLR
        // allows unboxing it straight to our identically-ordered EnumType.
        var type = (EnumType)ctx.Attributes[0].ConstructorArguments[0].Value!;

        return new EnumToGenerate(ns, type, declaration.Identifier.ToString());
    }

    // Output step: emit the typed backing property for the partial class.
    private static string Build(EnumToGenerate model)
    {
        var backing = model.Type switch
        {
            EnumType.Int => "int",
            EnumType.String => "string",
            EnumType.Guid => "global::System.Guid",
            EnumType.Byte => "byte",
            _ => "int",
        };

        return $$"""
            // <auto-generated /> — regenerated by EnumGenerator on every build; do not edit.
            #nullable enable

            namespace {{model.Namespace}}
            {
                partial class {{model.ClassName}}
                {
                    /// <summary>Strongly-typed backing value; type chosen by [GeneratedEnum(EnumType.{{model.Type}})].</summary>
                    public {{backing}} Value { get; init; }
                }
            }

            """;
    }

    // Injected into every consuming compilation via post-initialization.
    // KEEP the EnumType members in the SAME order as the enum below — the
    // generator unboxes the attribute value against that ordering.
    private const string MarkerSource = """
        // <auto-generated /> — injected by EnumGenerator.
        #nullable enable
        using System;

        namespace MyApp.CodeGen
        {
            internal enum EnumType { Int, String, Guid, Byte }

            [AttributeUsage(AttributeTargets.Class)]
            internal sealed class GeneratedEnumAttribute : Attribute
            {
                public GeneratedEnumAttribute(EnumType type) => Type = type;

                public EnumType Type { get; }
            }
        }
        """;
}

/// <summary>Generator-side copy of the enum (must match <c>MarkerSource</c> order).</summary>
public enum EnumType
{
    Int,
    String,
    Guid,
    Byte,
}

/// <summary>
/// Equatable model flowing through the pipeline. Being a <c>readonly record
/// struct</c> gives it value equality — the reason the incremental pipeline can
/// cache and skip regeneration when nothing changed.
/// </summary>
public readonly record struct EnumToGenerate(string Namespace, EnumType Type, string ClassName);
