namespace MyApp.CodeGen;

/// <summary>
/// The template. Everything the compiler writes per enum lives here, so
/// <see cref="EnumGenerator"/> stays a pipeline and nothing else.
///
/// Add a rule — a third serializer, a different EF mapping — and you change it
/// once, here. That is the whole argument against letting an agent copy-paste
/// the same converters into N files.
/// </summary>
internal static class EnumBuilder
{
    // Where the hand-written SmartEnum<T> / IntEnum<T> / ... bases live.
    private const string AbstractionsNamespace = "MyApp.Demo.Abstractions";

    public static string BuildCode(this EnumToGenerate @enum)
    {
        var name = @enum.ClassName;

        var (baseType, backing, readValue) = @enum.Type switch
        {
            EnumType.Int => ("IntEnum", "int", "reader.GetInt32()"),
            EnumType.String => ("StringEnum", "string", "reader.GetString()"),
            EnumType.Guid => ("GuidEnum", "global::System.Guid", "reader.GetGuid()"),
            EnumType.Byte => ("ByteEnum", "byte", "reader.GetByte()"),
            _ => ("IntEnum", "int", "reader.GetInt32()"),
        };

        var writeValue = @enum.Type is EnumType.String or EnumType.Guid
            ? "writer.WriteStringValue(value.Value)"
            : "writer.WriteNumberValue(value.Value)";

        // Strings match case-insensitively; everything else compares by value.
        var matchJson = @enum.Type == EnumType.String
            ? "string.Equals(x.Value, value, global::System.StringComparison.OrdinalIgnoreCase)"
            : "x.Value == value";

        var matchSql = @enum.Type == EnumType.String
            ? "string.Equals(a.Value, x, global::System.StringComparison.OrdinalIgnoreCase)"
            : "a.Value == x";

        return $$"""
            // <auto-generated /> — regenerated by EnumGenerator on every build; do not edit.
            using System.Linq;
            using System.Text.Json;
            using System.Text.Json.Serialization;
            using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
            using {{AbstractionsNamespace}};

            #nullable enable

            namespace {{@enum.Namespace}};

            // The base list is the load-bearing part: it brings in the typed Value and
            // the All lookup. Delete [GeneratedEnum] and this class stops compiling.
            [JsonConverter(typeof({{name}}JsonConverter))]
            public sealed partial class {{name}} : {{baseType}}<{{name}}>;

            /// <summary>
            /// System.Text.Json converter. Serializes as the bare backing value, so the
            /// wire format is {{backing}} rather than an object — and every {{name}}
            /// round-trips back to the same instance.
            /// </summary>
            public sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
            {
                public override {{name}} Read(ref Utf8JsonReader reader, global::System.Type typeToConvert, JsonSerializerOptions options)
                {
                    // Read into a local first: Utf8JsonReader is a ref struct passed by
                    // ref, and a ref parameter cannot be captured by the lambda below.
                    var value = {{readValue}};
                    return {{name}}.All.Single(x => {{matchJson}});
                }

                public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
                {
                    {{writeValue}};
                }
            }

            /// <summary>
            /// EF Core value converter: stores the backing value in the column and
            /// rehydrates the member on the way back.
            /// </summary>
            public sealed class {{name}}SqlConverter() : ValueConverter<{{name}}, {{backing}}>
            (
                convertToProviderExpression:   x => x.Value,
                convertFromProviderExpression: x => {{name}}.All.Single(a => {{matchSql}})
            );

            """;
    }
}
