using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MyApp.CodeGen;

/// <summary>
/// Incremental source generator. One attribute on a partial class becomes the
/// single source of truth; the compiler emits the repetitive companion code.
///
/// Per annotated class it emits:
///  - the base list — <c>: IntEnum&lt;Priority&gt;</c> — picked from the EnumType
///    on the attribute, which is where the typed <c>Value</c> and the <c>All</c>
///    lookup come from,
///  - a System.Text.Json converter (<c>{Class}JsonConverter</c>) plus the
///    <c>[JsonConverter]</c> attribute that wires it up,
///  - an EF Core value converter (<c>{Class}SqlConverter</c>).
///
/// Note what it does NOT emit: <c>All</c>. That lives in the hand-written
/// <c>SmartEnum&lt;T&gt;</c> base, where each member registers itself from the
/// constructor. Generate the wiring, hand-write the mechanism.
///
/// That is the talk in miniature: dozens of lines of converter boilerplate per
/// enum, written once in a template instead of copy-pasted N times. The demo's
/// <c>Priority</c> class does not compile without it — generation is
/// load-bearing, not cosmetic.
///
/// Why this is fast:
///  - IIncrementalGenerator (not the legacy ISourceGenerator).
///  - ForAttributeWithMetadataName -> only annotated nodes enter the pipeline.
///  - The model is an equatable readonly record struct, so the pipeline caches
///    and re-generates only when the model actually changes.
///  - The transform step is pure and small; text building happens in the output
///    step, in <see cref="EnumBuilder"/>.
/// </summary>
[Generator]
public sealed class EnumGenerator : IIncrementalGenerator
{
    // The demo injects the attribute instead of shipping it in a runtime assembly,
    // so it names it by metadata name rather than typeof(...).FullName.
    private const string AttributeMetadataName = "MyApp.CodeGen.GeneratedEnumAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the marker attribute + EnumType into the consuming compilation.
        // No shared runtime assembly needed — the attribute lives where it's used.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GeneratedEnumAttribute.g.cs", MarkerSource));

        var enums = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (attrCtx, _) => GetEnumToGenerate(attrCtx));

        context.RegisterSourceOutput(enums, static (spc, model) =>
            spc.AddSource($"{model.ClassName}.g.cs", model.BuildCode()));
    }

    // Pure: extract just the data we need. Returns an equatable value type.
    private static EnumToGenerate GetEnumToGenerate(GeneratorAttributeSyntaxContext ctx)
    {
        var @enum = (ClassDeclarationSyntax)ctx.TargetNode;

        var codeNamespace = @enum.FirstAncestorOrSelf<BaseNamespaceDeclarationSyntax>()?.Name.ToString()
                            ?? "GeneratedNamespace";

        // TypedConstant.Value for an enum is the boxed underlying int; the CLR
        // allows unboxing it straight to our identically-ordered EnumType.
        var type = (EnumType)ctx.Attributes[0].ConstructorArguments[0].Value!;

        return new EnumToGenerate(codeNamespace, type, @enum.Identifier.ToString());
    }

    // Injected into every consuming compilation via post-initialization.
    // KEEP the EnumType members in the SAME order as the enum below — the
    // generator unboxes the attribute value against that ordering.
    private const string MarkerSource = """
        // <auto-generated /> — injected by EnumGenerator.
        #nullable enable
        using System;

        namespace MyApp.CodeGen
        {
            internal enum EnumType { Int, String, Guid, Byte }

            [AttributeUsage(AttributeTargets.Class)]
            internal sealed class GeneratedEnumAttribute : Attribute
            {
                public GeneratedEnumAttribute(EnumType type) => Type = type;

                public EnumType Type { get; }
            }
        }
        """;
}

/// <summary>Generator-side copy of the enum (must match <c>MarkerSource</c> order).</summary>
public enum EnumType
{
    Int,
    String,
    Guid,
    Byte,
}

/// <summary>
/// Equatable model flowing through the pipeline. Being a <c>readonly record
/// struct</c> gives it value equality — the reason the incremental pipeline can
/// cache and skip regeneration when nothing changed.
/// </summary>
public readonly record struct EnumToGenerate(string Namespace, EnumType Type, string ClassName);
