using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using MyApp.CodeGen;
using MyApp.Tooling.Tests.Infrastructure;

namespace MyApp.Tooling.Tests.CodeGen;

/// <summary>
/// What <see cref="EnumGenerator"/> writes. The generated text is the contract
/// between the generator and every consuming project, so these tests assert on the
/// shape of it — and, in <see cref="GeneratedCode_CompilesAgainstTheAbstractions"/>,
/// on the only thing that finally matters: it compiles.
/// </summary>
public sealed class EnumGeneratorTests
{
    [Fact]
    public void PostInitialization_InjectsTheMarkerAttribute()
    {
        var result = GeneratorRunner.Run(TestCompilation.Create("// nothing to generate from"));

        var marker = result.Source("GeneratedEnumAttribute.g.cs");

        Assert.Contains("namespace MyApp.CodeGen", marker);
        Assert.Contains("internal sealed class GeneratedEnumAttribute : Attribute", marker);
        Assert.Contains("[AttributeUsage(AttributeTargets.Class)]", marker);
    }

    /// <summary>
    /// The generator unboxes the attribute argument straight into its own
    /// <see cref="EnumType"/>, which only works while the injected enum and the
    /// compiled one declare their members in the same order. Nothing in the
    /// compiler enforces that — this test does.
    /// </summary>
    [Fact]
    public void InjectedEnumType_DeclaresTheSameMembersInTheSameOrderAsTheGeneratorSideEnum()
    {
        var result = GeneratorRunner.Run(TestCompilation.Create("// nothing to generate from"));

        var injected = CSharpSyntaxTree
            .ParseText(
                result.Source("GeneratedEnumAttribute.g.cs"),
                TestCompilation.ParseOptions,
                cancellationToken: TestContext.Current.CancellationToken)
            .GetRoot(TestContext.Current.CancellationToken)
            .DescendantNodes()
            .OfType<EnumDeclarationSyntax>()
            .Single(e => e.Identifier.Text == "EnumType")
            .Members
            .Select(m => m.Identifier.Text);

        Assert.Equal(Enum.GetNames<EnumType>(), injected);
    }

    [Fact]
    public void AnnotatedClass_GetsItsBaseListJsonConverterAndSqlConverter()
    {
        var result = GeneratorRunner.Run(TestCompilation.Create(EnumSource(EnumType.Int)));

        var generated = result.Source("Priority.g.cs");

        // The base list is the load-bearing part: without it the hand-written
        // partial has no Value and no All, and stops compiling.
        Assert.Contains("public sealed partial class Priority : IntEnum<Priority>;", generated);
        Assert.Contains("[JsonConverter(typeof(PriorityJsonConverter))]", generated);
        Assert.Contains("public sealed class PriorityJsonConverter : JsonConverter<Priority>", generated);
        Assert.Contains("public sealed class PrioritySqlConverter() : ValueConverter<Priority, int>", generated);
        Assert.StartsWith("// <auto-generated />", generated);
    }

    [Theory]
    [InlineData(EnumType.Int, "IntEnum", "int", "reader.GetInt32()", "writer.WriteNumberValue")]
    [InlineData(EnumType.String, "StringEnum", "string", "reader.GetString()", "writer.WriteStringValue")]
    [InlineData(EnumType.Guid, "GuidEnum", "global::System.Guid", "reader.GetGuid()", "writer.WriteStringValue")]
    [InlineData(EnumType.Byte, "ByteEnum", "byte", "reader.GetByte()", "writer.WriteNumberValue")]
    public void BackingType_SelectsTheBaseTheColumnTypeAndBothJsonCalls(
        EnumType type, string baseType, string backing, string readValue, string writeValue)
    {
        var result = GeneratorRunner.Run(TestCompilation.Create(EnumSource(type)));

        var generated = result.Source("Priority.g.cs");

        Assert.Contains($"class Priority : {baseType}<Priority>;", generated);
        Assert.Contains($"ValueConverter<Priority, {backing}>", generated);
        Assert.Contains(readValue, generated);
        Assert.Contains($"{writeValue}(value.Value)", generated);
    }

    /// <summary>
    /// Strings are matched case-insensitively on the way back in; every other
    /// backing type compares by value. Both converters have to agree on that.
    /// </summary>
    [Theory]
    [InlineData(EnumType.String, true)]
    [InlineData(EnumType.Int, false)]
    [InlineData(EnumType.Guid, false)]
    [InlineData(EnumType.Byte, false)]
    public void OnlyStringEnums_MatchCaseInsensitively(EnumType type, bool expected)
    {
        var result = GeneratorRunner.Run(TestCompilation.Create(EnumSource(type)));

        var generated = result.Source("Priority.g.cs");

        Assert.Equal(expected, generated.Contains("StringComparison.OrdinalIgnoreCase"));
        Assert.Equal(expected, generated.Contains("string.Equals(x.Value, value"));
        Assert.Equal(!expected, generated.Contains("x.Value == value"));
    }

    [Fact]
    public void GeneratedCode_CompilesAgainstTheAbstractions()
    {
        GeneratorRunner.Run(TestCompilation.Create(EnumSource(EnumType.Int)), out var output);

        output.AssertCompiles();
    }

    [Theory]
    [InlineData(EnumType.Int, "1")]
    [InlineData(EnumType.String, "\"low\"")]
    [InlineData(EnumType.Byte, "(byte)1")]
    public void GeneratedCode_CompilesForEveryBackingType(EnumType type, string value)
    {
        var source = $$"""
            using MyApp.CodeGen;

            namespace MyApp.Demo;

            [GeneratedEnum(EnumType.{{type}})]
            public sealed partial class Priority
            {
                public static Priority Low { get; } = new() { Value = {{value}} };
            }
            """;

        GeneratorRunner.Run(TestCompilation.Create(source), out var output);

        output.AssertCompiles();
    }

    [Fact]
    public void GeneratedPartial_LandsInTheSameNamespaceAsTheAnnotatedClass()
    {
        var result = GeneratorRunner.Run(
            TestCompilation.Create(EnumSource(EnumType.Int, @namespace: "Acme.Billing.Domain")));

        Assert.Contains("namespace Acme.Billing.Domain;", result.Source("Priority.g.cs"));
    }

    /// <summary>
    /// Documents the fallback rather than endorsing it: a top-level class lands in
    /// "GeneratedNamespace", which does not merge with the hand-written partial.
    /// Put the class in a namespace.
    /// </summary>
    [Fact]
    public void ClassOutsideANamespace_FallsBackToGeneratedNamespace()
    {
        var source = """
            using MyApp.CodeGen;

            [GeneratedEnum(EnumType.Int)]
            public sealed partial class Priority;
            """;

        var result = GeneratorRunner.Run(TestCompilation.Create(source));

        Assert.Contains("namespace GeneratedNamespace;", result.Source("Priority.g.cs"));
    }

    [Fact]
    public void ClassWithoutTheAttribute_GeneratesNothingButTheMarker()
    {
        var source = """
            namespace MyApp.Demo;

            public sealed partial class Priority;
            """;

        var result = GeneratorRunner.Run(TestCompilation.Create(source));

        var generated = Assert.Single(result.GeneratedSources);
        Assert.Equal("GeneratedEnumAttribute.g.cs", generated.HintName);
    }

    [Fact]
    public void EveryAnnotatedClass_GetsItsOwnFile()
    {
        var result = GeneratorRunner.Run(TestCompilation.Create(
            EnumSource(EnumType.Int),
            EnumSource(EnumType.String, className: "Channel")));

        Assert.Equal(
            ["Channel.g.cs", "GeneratedEnumAttribute.g.cs", "Priority.g.cs"],
            result.GeneratedSources.Select(s => s.HintName).Order());
    }

    [Fact]
    public void Generator_ReportsNoDiagnosticsOfItsOwn()
    {
        var result = GeneratorRunner.Run(TestCompilation.Create(EnumSource(EnumType.Int)));

        Assert.Null(result.Exception);
        Assert.Empty(result.Diagnostics);
    }

    private static string EnumSource(
        EnumType type,
        string @namespace = "MyApp.Demo",
        string className = "Priority") => $$"""
            using MyApp.CodeGen;

            namespace {{@namespace}};

            [GeneratedEnum(EnumType.{{type}})]
            public sealed partial class {{className}}
            {
                public required string Name { get; init; }
            }
            """;
}
